---
namespace: lenmail
name: monitoring
version: 0.1.0
readme: README.md
authors:
- Dominik Lenhardt <dominik.lenhardt@lenmail.de>
description: Collection with monitoring roles for exporters, metrics storage, logging, and dashboards.
license:
- MIT
tags:
- monitoring
- observability
- prometheus
- grafana
- linux
dependencies:
  community.general: ">=3.0.0"
  ansible.posix: ">=1.4.0"
  community.crypto: ">=2.0.0"
repository: https://github.com/lenmail/ansible-collection-monitoring
documentation: https://github.com/lenmail/ansible-collection-monitoring
issues: https://github.com/lenmail/ansible-collection-monitoring/issues
build_ignore:
- .github/
- .git/
- .venv/
- .ansible/
- tests/
- dev_notes/
