---
- name: create system group
  ansible.builtin.group:
    name: "grafana-agent"
    system: true
    state: present
  become: true
  tags: grafana_agent

- name: create system user
  ansible.builtin.user:
    name: "grafana-agent"
    system: true
    shell: "/sbin/nologin"
    groups: "grafana-agent,adm,systemd-journal"
    createhome: false
  become: true
  tags: grafana_agent

- name: check if is installed
  ansible.builtin.stat:
    path: "/usr/local/bin/grafana_agent"
  register: __grafana_agent_is_installed
  become: true
  tags: grafana_agent

- name: gather currently installed version (if any)
  ansible.builtin.command: "/usr/local/bin/grafana_agent -version"
  changed_when: false
  register: __grafana_agent_current_version_output
  when: __grafana_agent_is_installed.stat.exists
  become: true
  tags: grafana_agent

- name: download binary to local folder
  ansible.builtin.get_url:
    url: "https://github.com/grafana/agent/releases/download/v{{ grafana_agent_version }}/grafana-agent-linux-{{ go_arch }}.zip"
    dest: "/tmp/grafana_agent-{{ grafana_agent_version }}.linux-{{ go_arch }}.zip"
    mode: "0644"
  #environment: "{{ proxy_env }}"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false
  become: true
  tags: grafana_agent
  when: (not __grafana_agent_is_installed.stat.exists) or (__grafana_agent_current_version_output.stdout_lines[0].split(" ")[2] != grafana_agent_version)

- name: unpack binary
  ansible.builtin.unarchive:
    src: "/tmp/grafana_agent-{{ grafana_agent_version }}.linux-{{ go_arch }}.zip"
    dest: "/tmp"
  delegate_to: localhost
  check_mode: false
  become: true
  tags: grafana_agent
  when: (not __grafana_agent_is_installed.stat.exists) or (__grafana_agent_current_version_output.stdout_lines[0].split(" ")[2] != grafana_agent_version)

- name: propagate binaries
  ansible.builtin.copy:
    src: "/tmp/grafana-agent-linux-{{ go_arch }}"
    dest: "/usr/local/bin/grafana_agent"
    mode: 0755
    owner: root
    group: root
  notify: restart grafana_agent
  become: true
  tags: grafana_agent
  when: (not __grafana_agent_is_installed.stat.exists) or (__grafana_agent_current_version_output.stdout_lines[0].split(" ")[2] != grafana_agent_version)

- name: create config directory
  ansible.builtin.file:
    path: "/var/lib/grafana-agent"
    state: directory
    owner: grafana-agent
    group: grafana-agent
    mode: 0755
  become: true
  tags: grafana_agent

- name: create config directory
  ansible.builtin.file:
    path: "/var/lib/grafana-agent-textfile"
    state: directory
    owner: grafana-agent
    group: grafana-agent
    mode: 0777
  become: true
  tags: grafana_agent

- name: generate config file
  ansible.builtin.copy:
    content: "{{ grafana_agent_config | to_nice_yaml(indent=2, sort_keys=False) }}\n"
    dest: "/etc/grafana-agent.yaml"
    owner: "grafana-agent"
    group: "grafana-agent"
    mode: 0644
  notify: reload grafana_agent
  become: true
  tags:
  - grafana_agent
  - grafana_agent_config

- name: create systemd service unit
  ansible.builtin.template:
    src: grafana_agent.service.j2
    dest: /etc/systemd/system/grafana_agent.service
    owner: root
    group: root
    mode: 0644
  notify: restart grafana_agent
  become: true
  tags: grafana_agent

- name: ensure service is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: grafana_agent
    enabled: true
    state: started
  become: true
  tags: grafana_agent
