---
- name: Create system group
  ansible.builtin.group:
    name: "{{ unifi_poller_system_group }}"
    system: true
    state: present
  when: unifi_poller_system_group != "root"
  become: true
  tags: unifi_poller

- name: Create system user
  ansible.builtin.user:
    name: "{{ unifi_poller_system_user }}"
    system: true
    shell: "/sbin/nologin"
    group: "{{ unifi_poller_system_group }}"
    createhome: false
  when: unifi_poller_system_user != "root"
  become: true
  tags: unifi_poller

- name: Create configuration directory
  ansible.builtin.file:
    path: "{{ unifi_poller_config_path }}"
    state: directory
    owner: "{{ unifi_poller_system_user }}"
    group: "{{ unifi_poller_system_group }}"
    mode: "0755"
  become: true
  tags: unifi_poller

- name: Check if unifi_poller is installed
  ansible.builtin.stat:
    path: "{{ unifi_poller_binary_install_dir }}/unifi_poller"
  register: __unifi_poller_is_installed
  become: true
  tags: unifi_poller

- name: Gather currently installed unifi_poller version
  ansible.builtin.command: "{{ unifi_poller_binary_install_dir }}/unifi_poller --version"
  changed_when: false
  register: __unifi_poller_current_version_output
  when: __unifi_poller_is_installed.stat.exists
  become: true
  tags: unifi_poller

- name: Determine whether installation or upgrade is required
  ansible.builtin.set_fact:
    __unifi_poller_install_required: >-
      {{ (not __unifi_poller_is_installed.stat.exists)
         or (__unifi_poller_current_version_output.stdout_lines[0].split(" ")[2] != unifi_poller_version) }}
  tags: unifi_poller

- name: Fetch checksum list on localhost
  ansible.builtin.set_fact:
    _checksums: "{{ lookup('url', 'https://github.com/unpoller/unpoller/releases/download/v' + unifi_poller_version + '/checksums.sha256.txt', wantlist=True) | list }}"
  environment: "{{ proxy_env }}"
  delegate_to: localhost
  run_once: true
  become: true
  tags: unifi_poller
  when: __unifi_poller_install_required

- name: Select checksum for {{ go_arch }} architecture
  ansible.builtin.set_fact:
    unifi_poller_checksum: "{{ item.split(' ')[0] }}"
  with_items: "{{ _checksums }}"
  delegate_to: localhost
  when:
  - "('unifi-poller.' + go_arch + '.linux.gz') in item"
  - __unifi_poller_install_required
  become: true
  tags: unifi_poller

- name: Download binary on localhost
  ansible.builtin.get_url:
    url: "https://github.com/unpoller/unpoller/releases/download/v{{ unifi_poller_version }}/unifi-poller.{{ go_arch }}.linux.gz"
    dest: "/tmp/unifi_poller-{{ unifi_poller_version }}.linux-{{ go_arch }}.gz"
    checksum: "sha256:{{ unifi_poller_checksum }}"
    mode: "0644"
  environment: "{{ proxy_env }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false
  become: true
  tags: unifi_poller
  when: __unifi_poller_install_required

- name: Unpack binary on localhost
  ansible.builtin.command:
    cmd: "/usr/bin/gzip -f -d /tmp/unifi_poller-{{ unifi_poller_version }}.linux-{{ go_arch }}.gz"
    creates: "/tmp/unifi_poller-{{ unifi_poller_version }}.linux-{{ go_arch }}"
  delegate_to: localhost
  check_mode: false
  become: true
  tags: unifi_poller
  when: __unifi_poller_install_required

- name: Install unifi_poller binary
  ansible.builtin.copy:
    src: "/tmp/unifi_poller-{{ unifi_poller_version }}.linux-{{ go_arch }}"
    dest: "{{ unifi_poller_binary_install_dir }}/unifi_poller"
    mode: "0755"
    owner: "root"
    group: "root"
  notify: restart unifi_poller
  become: true
  tags: unifi_poller
  when: __unifi_poller_install_required

- name: Render configuration
  ansible.builtin.template:
    force: true
    src: config.yaml.j2
    dest: "{{ unifi_poller_config_path }}/config.yaml"
    owner: "{{ unifi_poller_system_user }}"
    group: "{{ unifi_poller_system_group }}"
    mode: "0640"
  notify: restart unifi_poller
  become: true
  tags:
  - unifi_poller
  - unifi_poller_config

- name: Install systemd service unit
  ansible.builtin.template:
    src: unifi_poller.service.j2
    dest: /etc/systemd/system/unifi_poller.service
    owner: root
    group: root
    mode: "0644"
  notify: restart unifi_poller
  become: true
  tags: unifi_poller

- name: Ensure service is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: unifi_poller
    enabled: "{{ unifi_poller_service_enabled }}"
    state: "{{ unifi_poller_service_state }}"
  become: true
  tags: unifi_poller
  when: unifi_poller_manage_service
