---
# https://docs.ansible.com/ansible/latest/user_guide/playbooks_tags.html#tag-inheritance-for-includes-blocks-and-the-apply-keyword
- name: Include vars with any tags
  block:
  - name: Include os-specific variables
    include_vars: "{{ ansible_distribution | lower }}.yml"
  tags:
  - always

- name: Install Vector using the official setup script
  ansible.builtin.shell: "set -o pipefail && curl -L https://setup.vector.dev | bash"
  args:
    executable: /bin/bash
  tags: vector
  changed_when: "'already installed' not in (vector_install_script.stdout | default(''))"
  register: vector_install_script

- name: "Install vector"
  ansible.builtin.package:
    name: vector
    state: latest
  tags: vector

- name: Remove default vector config
  file:
    path: /etc/vector/vector.toml
    state: absent
  when: vector_configure_rm_default | bool
  tags: vector

- name: Set vector config file path
  template:
    src: vector.default.j2
    dest: /etc/default/vector
    mode: "0644"
  notify:
  - restart vector
  tags: vector

- name: Provide configuration file
  template:
    src: vector.yaml.j2
    dest: "{{ vector_configure_config_path }}"
    mode: 0644
  notify:
  - reload vector
  tags: vector

- name: Start and enable service
  systemd:
    name: vector
    enabled: "true"
    state: "started"
  tags: vector
