---
- name: restart grafana_agent
  ansible.builtin.systemd:
    daemon_reload: true
    name: grafana_agent
    state: restarted
  become: true
  tags: grafana_agent

- name: reload grafana_agent
  ansible.builtin.systemd:
    name: grafana_agent
    state: reloaded
  become: true
  tags: grafana_agent
