{
 "title": "Windows Exporter",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "hostname",
    "label": "Host",
    "query": {
     "query": "label_values(windows_os_info,instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Host Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_os_time{instance=~\"$hostname\"} - windows_system_system_up_time{instance=~\"$hostname\"}"
    }
   ]
  },
  {
   "title": "Processors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_cs_logical_processors{instance=~\"$hostname\"}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "windows_cs_physical_memory_bytes{instance=~\"$hostname\"}"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - avg(irate(windows_cpu_time_total{instance=~\"$hostname\",mode=\"idle\"}[5m])) > 0"
    }
   ]
  },
  {
   "title": "Memory Load",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (windows_os_physical_memory_free_bytes{instance=~\"$hostname\"} / windows_cs_physical_memory_bytes{instance=~\"$hostname\"}) > 0"
    }
   ]
  },
  {
   "title": "Disk Use",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "1 - (sum(windows_logical_disk_free_bytes{instance=~\"$hostname\",volume=~\"^[A-Z]:.*$\"}) / sum(windows_logical_disk_size_bytes{instance=~\"$hostname\",volume=~\"^[A-Z]:.*$\"})) > 0"
    }
   ]
  },
  {
   "title": "Net IN (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 15, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_received_total{instance=~\"$hostname\"}[24h]))"
    }
   ]
  },
  {
   "title": "Net OUT (24h)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 17, "y": 1 },
   "repeat": "host",
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(windows_net_bytes_sent_total{instance=~\"$hostname\"}[24h]))"
    }
   ]
  },
  {
   "title": "Disk (Free)",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "repeat": "host",
   "targets": [
    {
     "expr": "sort_desc(windows_logical_disk_free_bytes{instance=~\"$hostname\",volume=~\"(^[A-Z]:$)\"})"
    }
   ]
  },
  { "title": "CPU Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "repeat": "host",
   "yaxes": [
    { "format": "short", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "1 - avg(irate(windows_cpu_time_total{instance=~\"$hostname\",mode=\"idle\"}[5m]))",
     "legendFormat": "{{mode}}"
    }
   ]
  },
  {
   "title": "System Exceptions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 6 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(windows_system_exception_dispatches_total{instance=~\"$hostname\"}[5m])",
     "legendFormat": "exceptions"
    }
   ]
  },
  {
   "title": "System Threads",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 6 },
   "repeat": "host",
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "windows_system_threads{instance=~\"$hostname\"}",
     "legendFormat": "threads"
    }
   ]
  },
  { "title": "Memory Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 14 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes", "label": "RAM" }
   ],
   "targets": [
    {
     "expr": "windows_os_virtual_memory_bytes{instance=~\"$hostname\"} > 0",
     "legendFormat": "Virtual"
    },
    {
     "expr": "windows_cs_physical_memory_bytes{instance=~\"$hostname\"} > 0",
     "legendFormat": "Physical"
    },
    {
     "expr": "windows_os_physical_memory_free_bytes{instance=~\"$hostname\"} > 0",
     "legendFormat": "Free"
    }
   ]
  },
  { "title": "Network Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 } },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "irate(windows_net_bytes_received_total{instance=~\"$hostname\",nic!~\"(?i).*(isatap|tunneling).*$\"}[5m]) > 0",
     "legendFormat": "Received"
    },
    {
     "expr": "- irate(windows_net_bytes_sent_total{instance=~\"$hostname\",nic!~\"(?i).*(isatap|tunneling).*$\"}[5m]) < 0",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "Network discarded/error",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "repeat": "host",
   "yaxes": [
    { "format": "pps", "label": "Load" }
   ],
   "targets": [
    {
     "expr": "irate(windows_net_packets_outbound_discarded{instance=~\"$hostname\",nic!~\"isatap.+\"}[5m]) + irate(windows_net_packets_outbound_errors{instance=~\"$hostname\"}[5m])",
     "legendFormat": "Sent ({{nic}})"
    },
    {
     "expr": "irate(windows_net_packets_received_discarded{instance=~\"$hostname\", nic!~\"isatap.+\"}[5m]) + irate(windows_net_packets_received_errors{instance=~\"$hostname\"}[5m])",
     "legendFormat": "Received ({{nic}})"
    }
   ]
  },
  { "title": "Disk Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Disk (Free)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 29 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "windows_logical_disk_free_bytes{instance=~\"$hostname\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}",
     "legendFormat": "{{volume}}"
    }
   ]
  },
  {
   "title": "Disk Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 29 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "- irate(windows_logical_disk_write_bytes_total{instance=~\"$hostname\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
     "legendFormat": "Write {{volume}}"
    },
    {
     "expr": "irate(windows_logical_disk_read_bytes_total{instance=~\"$hostname\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
     "legendFormat": "Read {{volume}}"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 29 },
   "repeat": "host",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "- irate(windows_logical_disk_write_seconds_total{instance=~\"$hostname\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) < 0",
     "legendFormat": "Write {{volume}}"
    },
    {
     "expr": "irate(windows_logical_disk_read_seconds_total{instance=~\"$hostname\", volume !~ \"(HarddiskVolume.+|[A-Z]:.+)\"}[5m]) > 0",
     "legendFormat": "Read {{volume}}"
    }
   ]
  }
 ]
}