---
- name: create system group
  ansible.builtin.group:
    name: "prometheus"
    system: true
    state: present
  become: true
  tags: blackbox_exporter

- name: create system user
  ansible.builtin.user:
    name: "prometheus"
    system: true
    shell: "/sbin/nologin"
    group: "prometheus"
    createhome: false
  become: true
  tags: blackbox_exporter

- name: create data directory
  ansible.builtin.file:
    path: "/etc/blackbox_exporter"
    state: directory
    owner: "prometheus"
    group: "prometheus"
    mode: 0755
  become: true
  tags: blackbox_exporter

- name: check if blackbox_exporter is installed
  ansible.builtin.stat:
    path: "/usr/local/bin/blackbox_exporter"
  register: __blackbox_exporter_is_installed
  become: true
  tags: blackbox_exporter

- name: gather currently installed blackbox_exporter version (if any)
  ansible.builtin.command: "/usr/local/bin/blackbox_exporter --version"
  changed_when: false
  register: __blackbox_exporter_current_version_output
  when: __blackbox_exporter_is_installed.stat.exists
  become: true
  tags: blackbox_exporter

- name: download binary to local folder
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/blackbox_exporter/releases/download/v{{ blackbox_exporter_version }}/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    mode: 0744
  #environment: "{{  proxy_env  }}"
  register: _download_binary
  until: _download_binary is succeeded
  retries: 5
  delay: 2
  delegate_to: localhost
  check_mode: false
  become: true
  tags: blackbox_exporter
  when: (not __blackbox_exporter_is_installed.stat.exists) or (__blackbox_exporter_current_version_output.stdout_lines[0].split(" ")[2] != blackbox_exporter_version)

- name: unpack binary
  ansible.builtin.unarchive:
    src: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ go_arch }}/blackbox_exporter"
  delegate_to: localhost
  check_mode: false
  become: true
  tags: blackbox_exporter
  when: (not __blackbox_exporter_is_installed.stat.exists) or (__blackbox_exporter_current_version_output.stdout_lines[0].split(" ")[2] != blackbox_exporter_version)

- name: propagate binaries
  ansible.builtin.copy:
    src: "/tmp/blackbox_exporter-{{ blackbox_exporter_version }}.linux-{{ go_arch }}/blackbox_exporter"
    dest: "/usr/local/bin/blackbox_exporter"
    mode: 0755
    owner: root
    group: root
  notify: restart blackbox_exporter
  become: true
  tags: blackbox_exporter
  when: (not __blackbox_exporter_is_installed.stat.exists) or (__blackbox_exporter_current_version_output.stdout_lines[0].split(" ")[2] != blackbox_exporter_version)

- name: generate config file
  ansible.builtin.copy:
    content: "{{ blackbox_exporter_config | to_nice_yaml(indent=2, sort_keys=False) }}\n"
    dest: "/etc/blackbox_exporter/config.yml"
    owner: "prometheus"
    group: "prometheus"
    mode: 0644
    validate: "/usr/local/bin/blackbox_exporter --config.file=\"%s\" --config.check"
  notify: restart blackbox_exporter
  become: true
  tags:
  - blackbox_exporter
  - blackbox_exporter_config

- name: generate webconfig file
  ansible.builtin.copy:
    content: "{{ blackbox_exporter_webconfig | to_nice_yaml(indent=2, sort_keys=False) }}\n"
    dest: "/etc/blackbox_exporter/web-config.yml"
    owner: "prometheus"
    group: "prometheus"
    mode: 0644
  notify: restart blackbox_exporter
  become: true
  when: blackbox_exporter_webconfig | length > 0
  tags:
  - blackbox_exporter
  - blackbox_exporter_config

- name: create systemd service unit
  ansible.builtin.template:
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
    owner: root
    group: root
    mode: 0644
  become: true
  tags: blackbox_exporter

- name: ensure blackbox exporter is enabled on boot
  ansible.builtin.systemd:
    daemon_reload: true
    name: blackbox_exporter
    enabled: true
    state: started
  become: true
  tags: blackbox_exporter
