---
- name: create system group
  ansible.builtin.group:
    name: "alertmanager"
    system: true
    state: present
  become: true
  tags: alertmanager

- name: create system user
  ansible.builtin.user:
    name: "alertmanager"
    system: true
    shell: "/usr/sbin/nologin"
    group: "alertmanager"
    createhome: false
  become: true
  tags: alertmanager

- name: create directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "alertmanager"
    group: "alertmanager"
    mode: 0755
  with_items:
  - "/etc/alertmanager"
  - "{{ alertmanager_config_dir }}/templates"
  - "/etc/jiralert"
  - "/var/lib/alertmanager"
  become: true
  tags: alertmanager

- name: check if is installed
  ansible.builtin.stat:
    path: "/usr/local/bin/alertmanager"
  register: __alertmanager_is_installed
  become: true
  tags: alertmanager

- name: gather currently installed version (if any)
  ansible.builtin.command: "/usr/local/bin/alertmanager --version"
  changed_when: false
  register: __alertmanager_current_version_output
  when: __alertmanager_is_installed.stat.exists
  become: true
  tags: alertmanager

- name: installed version
  ansible.builtin.debug:
    var: __alertmanager_current_version_output.stdout_lines[0].split(" ")[2]
  tags: alertmanager

- name: download binary to local folder
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/alertmanager/releases/download/v{{ alertmanager_version }}/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}.tar.gz"
    mode: "0644"
  #environment: "{{  proxy_env  }}"
  register: _download_archive
  delegate_to: localhost
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  # run_once: true # <-- this can't be set due to multi-arch support
  check_mode: false
  become: false
  tags: alertmanager
  when: (not __alertmanager_is_installed.stat.exists) or ((__alertmanager_current_version_output.stdout_lines[0].split(" ")[2] != alertmanager_version) and (alertmanager_localinstall is not defined))

- name: unpack binaries
  ansible.builtin.unarchive:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}/alertmanager"
  delegate_to: localhost
  check_mode: false
  become: false
  tags: alertmanager
  when: (not __alertmanager_is_installed.stat.exists) or ((__alertmanager_current_version_output.stdout_lines[0].split(" ")[2] != alertmanager_version) and (alertmanager_localinstall is not defined))

- name: copy binary
  ansible.builtin.copy:
    src: "/tmp/alertmanager-{{ alertmanager_version }}.linux-{{ go_arch }}/{{ item }}"
    dest: "/usr/local/bin/"
    mode: 0755
    owner: "alertmanager"
    group: "alertmanager"
  with_items:
  - alertmanager
  - amtool
  notify: restart alertmanager
  become: true
  tags: alertmanager
  when: (not __alertmanager_is_installed.stat.exists) or ((__alertmanager_current_version_output.stdout_lines[0].split(" ")[2] != alertmanager_version) and (alertmanager_localinstall is not defined))

- name: generate config file
  ansible.builtin.template:
    src: "alertmanager.config.j2"
    dest: "{{ alertmanager_config_dir }}/config.yml"
    owner: "alertmanager"
    group: "alertmanager"
    mode: 0644
    validate: "/usr/local/bin/amtool --alertmanager.url=  check-config %s"
  notify: reload alertmanager
  become: true
  tags:
  - alertmanager
  - alertmanager_config

- name: generate webconfig file
  ansible.builtin.copy:
    content: "{{ alertmanager_webconfig | to_nice_yaml(indent=2, sort_keys=False) }}\n"
    dest: "{{ alertmanager_config_dir }}/web-config.yml"
    owner: "alertmanager"
    group: "alertmanager"
    mode: 0644
  notify: restart alertmanager
  become: true
  when: alertmanager_webconfig | length > 0
  tags:
  - alertmanager
  - alertmanager_config

- name: copy template files
  ansible.builtin.copy:
    src: "alertmanager/default_{{ ansible_environment }}.tmpl"
    dest: "{{ alertmanager_config_dir }}/templates/default.tmpl"
    force: true
    owner: "alertmanager"
    group: "alertmanager"
    mode: 0644
  notify: reload alertmanager
  become: true
  tags:
  - alertmanager
  - alertmanager_template

- name: create systemd service unit
  ansible.builtin.template:
    src: alertmanager.service.j2
    dest: /etc/systemd/system/alertmanager.service
    owner: root
    group: root
    mode: 0644
  notify: restart alertmanager
  become: true
  tags: alertmanager

- name: start and enable alertmanager service
  ansible.builtin.systemd:
    daemon_reload: true
    name: alertmanager
    state: started
    enabled: true
  become: true
  tags: alertmanager
