---
argument_specs:
  main:
    short_description: Entry point for the promtail role.
    description:
    - Validate variables for the `promtail` role.
    options:
      proxy_env:
        description:
        - Controls `proxy_env` for the `promtail` role.
        required: false
        type: dict
      promtail_version:
        description:
        - Controls `promtail_version` for the `promtail` role.
        required: false
        type: str
      promtail_listen_port:
        description:
        - Controls `promtail_listen_port` for the `promtail` role.
        required: false
        type: int
      promtail_listen_address:
        description:
        - Controls `promtail_listen_address` for the `promtail` role.
        required: false
        type: str
      promtail_config_dir:
        description:
        - Controls `promtail_config_dir` for the `promtail` role.
        required: false
        type: str
      promtail_config_file:
        description:
        - Controls `promtail_config_file` for the `promtail` role.
        required: false
        type: str
      promtail_config_file_sd_dir:
        description:
        - Controls `promtail_config_file_sd_dir` for the `promtail` role.
        required: false
        type: str
      promtail_binary_install_dir:
        description:
        - Controls `promtail_binary_install_dir` for the `promtail` role.
        required: false
        type: str
      promtail_data_dir:
        description:
        - Controls `promtail_data_dir` for the `promtail` role.
        required: false
        type: str
      promtail_config_log_level:
        description:
        - Controls `promtail_config_log_level` for the `promtail` role.
        required: false
        type: str
      promtail_system_user:
        description:
        - Controls `promtail_system_user` for the `promtail` role.
        required: false
        type: str
      promtail_system_group:
        description:
        - Controls `promtail_system_group` for the `promtail` role.
        required: false
        type: str
      promtail_user_additional_groups:
        description:
        - Controls `promtail_user_additional_groups` for the `promtail` role.
        required: false
        type: str
      promtail_add_network_capabilities:
        description:
        - Controls `promtail_add_network_capabilities` for the `promtail` role.
        required: false
        type: bool
      promtail_config:
        description:
        - Controls `promtail_config` for the `promtail` role.
        required: false
        type: dict
