---
argument_specs:
  main:
    short_description: Entry point for the node_exporter role.
    description:
    - Validate variables for the `node_exporter` role.
    options:
      proxy_env:
        description:
        - Controls `proxy_env` for the `node_exporter` role.
        required: false
        type: dict
      node_exporter_version:
        description:
        - Controls `node_exporter_version` for the `node_exporter` role.
        required: false
        type: str
      node_exporter_web_listen_address:
        description:
        - Controls `node_exporter_web_listen_address` for the `node_exporter` role.
        required: false
        type: str
      node_exporter_binary_install_dir:
        description:
        - Controls `node_exporter_binary_install_dir` for the `node_exporter` role.
        required: false
        type: str
      node_exporter_web_listen_port:
        description:
        - Controls `node_exporter_web_listen_port` for the `node_exporter` role.
        required: false
        type: int
      node_exporter_system_user:
        description:
        - Controls `node_exporter_system_user` for the `node_exporter` role.
        required: false
        type: str
      node_exporter_system_group:
        description:
        - Controls `node_exporter_system_group` for the `node_exporter` role.
        required: false
        type: str
      node_exporter_user_additional_groups:
        description:
        - Controls `node_exporter_user_additional_groups` for the `node_exporter` role.
        required: false
        type: str
      node_exporter_create_consul_agent_service:
        description:
        - Controls `node_exporter_create_consul_agent_service` for the `node_exporter` role.
        required: false
        type: bool
      node_exporter_textfile_dir:
        description:
        - Controls `node_exporter_textfile_dir` for the `node_exporter` role.
        required: false
        type: str
      node_exporter_config_dir:
        description:
        - Controls `node_exporter_config_dir` for the `node_exporter` role.
        required: false
        type: str
      node_exporter_log_level:
        description:
        - Controls `node_exporter_log_level` for the `node_exporter` role.
        required: false
        type: str
      node_exporter_log_format:
        description:
        - Controls `node_exporter_log_format` for the `node_exporter` role.
        required: false
        type: str
      node_exporter_disable_go_metrics:
        description:
        - Controls `node_exporter_disable_go_metrics` for the `node_exporter` role.
        required: false
        type: bool
      node_exporter_textfile_collectors:
        description:
        - Controls `node_exporter_textfile_collectors` for the `node_exporter` role.
        required: false
        type: list
      node_exporter_tls_server_config:
        description:
        - Controls `node_exporter_tls_server_config` for the `node_exporter` role.
        required: false
        type: dict
      node_exporter_http_server_config:
        description:
        - Controls `node_exporter_http_server_config` for the `node_exporter` role.
        required: false
        type: dict
      node_exporter_basic_auth_users:
        description:
        - Controls `node_exporter_basic_auth_users` for the `node_exporter` role.
        required: false
        type: dict
      node_exporter_enabled_collectors:
        description:
        - Controls `node_exporter_enabled_collectors` for the `node_exporter` role.
        required: false
        type: list
        elements: dict
      node_exporter_disabled_collectors:
        description:
        - Controls `node_exporter_disabled_collectors` for the `node_exporter` role.
        required: false
        type: list
        elements: str
      node_exporter_webconfig:
        description:
        - Controls `node_exporter_webconfig` for the `node_exporter` role.
        required: false
        type: list
