---
argument_specs:
  main:
    short_description: Entry point for the grafana_agent role.
    description:
    - Validate variables for the `grafana_agent` role.
    options:
      proxy_env:
        description:
        - Controls `proxy_env` for the `grafana_agent` role.
        required: false
        type: dict
      grafana_agent_version:
        description:
        - Controls `grafana_agent_version` for the `grafana_agent` role.
        required: false
        type: str
      grafana_agent_config_flags_extra:
        description:
        - Controls `grafana_agent_config_flags_extra` for the `grafana_agent` role.
        required: false
        type: dict
      grafana_agent_config:
        description:
        - Controls `grafana_agent_config` for the `grafana_agent` role.
        required: false
        type: str
      defaults_grafana_agent_config:
        description:
        - Controls `defaults_grafana_agent_config` for the `grafana_agent` role.
        required: false
        type: dict
