---
proxy_env: {}
promtail_version: 3.3.0
promtail_listen_port: 9080
promtail_listen_address: 0.0.0.0
promtail_config_dir: /etc/promtail
promtail_config_file: config.yml
promtail_config_file_sd_dir: "{{ promtail_config_dir }}/file_sd"
promtail_binary_install_dir: /usr/local/bin
promtail_data_dir: /var/lib/promtail
promtail_config_log_level: warn
promtail_system_user: "{{ prometheus_user | default('loki') }}"
promtail_system_group: "{{ prometheus_user | default('loki') }}"
promtail_user_additional_groups: adm
promtail_add_network_capabilities: true
promtail_config:
  positions:
    filename: "{{ promtail_data_dir }}/positions.yaml"
  server:
#    disable: true
    http_listen_address: "{{ promtail_listen_address }}"
    http_listen_port: "{{ promtail_listen_port }}"
    grpc_listen_address: "{{ promtail_listen_address }}"
    grpc_listen_port: 0
    log_level: "{{ promtail_config_log_level }}"
  clients:
  - url: http://localhost:3100/loki/api/v1/push
    tenant_id: prime
    external_labels:
      node: "{{ inventory_hostname }}"
  scrape_configs:
    # Journald Scraping
  - job_name: journal
    journal:
        # Pfad zum Journal (default für System)
      path: /var/log/journal
      labels:
        job: systemd-journal
    relabel_configs:
    - source_labels: ['__journal__systemd_unit']
      target_label: 'unit'
    - source_labels: ['__journal__hostname']
      target_label: 'host'
    - source_labels: ['__journal__transport']
      target_label: 'transport'
    # # Syslog Input
    # - job_name: syslog
    #   syslog:
    #     listen_address: 0.0.0.0:514
    #     label_structured_data: true
    #   relabel_configs:
    #     - source_labels: ['__syslog_message_severity']
    #       target_label: 'severity'
    #     - source_labels: ['__syslog_message_app_name']
    #       target_label: 'app'
    #     - source_labels: ['__syslog_message_hostname']
    #       target_label: 'host'
  # HAProxy Logfile
  # - job_name: haproxy
  #   static_configs:
  #     - targets:
  #         - localhost
  #       labels:
  #         job: haproxy
  #         app: haproxy
  #         __path__: /var/log/haproxy.log
  #   pipeline_stages:
  #     - match:
  #         selector: '{job="haproxy"}'
  #         stages:
  #           - regex:
  #               expression: '^(?P<client_ip>\S+):(?P<client_port>\d+) \[(?P<timestamp>[^\]]+)\] (?P<frontend>\S+) (?P<backend>\S+)/(?P<server>\S+) (?P<response_time>\d+)/(?P<connect_time>\d+)/(?P<total_time>\d+)/(?P<status_code>\d+) (?P<bytes_out>\d+) .*'
  #           - labels:
  #               client_ip:
  #               client_port:
  #               frontend:
  #               backend:
  #               server:
  #               status_code:
  #               response_time:
  #               connect_time:
  #               total_time:
  #               bytes_out:
