---
proxy_env: {}
postgres_exporter_version: 0.11.1
postgres_exporter_config_flags_extra: {}
postgres_exporter_dbname: postgres
postgres_exporter_username: postgres
postgres_exporter_query_filename: queries-default.yml
postgres_exporter_data_source_name: "user={{ postgres_exporter_username }} dbname={{ postgres_exporter_dbname }} host=/var/run/postgresql/ sslmode=disable"
