---
- name: create system group
  ansible.builtin.group:
    name: prometheus
    system: true
    state: present
  become: true
  tags: prometheus

- name: create system user
  ansible.builtin.user:
    name: prometheus
    system: true
    shell: "/sbin/nologin"
    group: prometheus
    createhome: false
  become: true
  tags: prometheus

- name: create configuration and data directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: prometheus
    group: prometheus
    mode: 0755
  with_items:
  - "/etc/prometheus"
  - "/etc/prometheus/rules"
  - "/etc/prometheus/file_sd"
  - "/var/lib/prometheus"
  become: true
  tags: prometheus

- name: check if is installed
  ansible.builtin.stat:
    path: "/usr/local/bin/prometheus"
  register: __prometheus_is_installed
  become: true
  tags: prometheus

- name: gather currently installed version (if any)
  ansible.builtin.command: "/usr/local/bin/prometheus --version"
  changed_when: false
  register: __prometheus_current_version_output
  when: __prometheus_is_installed.stat.exists
  become: true
  tags: prometheus

- name: download binary to local folder
  ansible.builtin.get_url:
    url: "https://github.com/prometheus/prometheus/releases/download/v{{ prometheus_version }}/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
    mode: "0644"
  #environment: "{{ proxy_env }}"
  register: _download_archive
  until: _download_archive is succeeded
  retries: 5
  delay: 2
  # run_once: true # <-- this cannot be set due to multi-arch support
  delegate_to: localhost
  check_mode: false
  become: true
  tags: prometheus
  when: (not __prometheus_is_installed.stat.exists) or (__prometheus_current_version_output.stdout_lines[0].split(" ")[2] != prometheus_version)

- name: unpack binaries
  ansible.builtin.unarchive:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}.tar.gz"
    dest: "/tmp"
    creates: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}/prometheus"
  delegate_to: localhost
  check_mode: false
  become: true
  tags: prometheus
  when: (not __prometheus_is_installed.stat.exists) or (__prometheus_current_version_output.stdout_lines[0].split(" ")[2] != prometheus_version)

- name: propagate binaries
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}/{{ item }}"
    dest: "/usr/local/bin/{{ item }}"
    mode: 0755
    owner: root
    group: root
  with_items:
  - prometheus
  - promtool
  notify: restart prometheus
  become: true
  tags: prometheus
  when: (not __prometheus_is_installed.stat.exists) or (__prometheus_current_version_output.stdout_lines[0].split(" ")[2] != prometheus_version)

- name: propagate console templates
  ansible.builtin.copy:
    src: "/tmp/prometheus-{{ prometheus_version }}.linux-{{ go_arch }}/{{ item }}/"
    dest: "/etc/prometheus/{{ item }}/"
    mode: 0644
    owner: prometheus
    group: prometheus
  with_items:
  - console_libraries
  - consoles
  notify: restart prometheus
  become: true
  tags: prometheus
  when: (not __prometheus_is_installed.stat.exists) or (__prometheus_current_version_output.stdout_lines[0].split(" ")[2] != prometheus_version)

- name: register alertrules
  ansible.builtin.find:
    paths: /etc/prometheus/rules
    file_type: file
    recurse: false
  register: alertrule_files
  become: true
  tags:
  - prometheus
  - prometheus_alertrules

- name: remove unmanaged alertrules
  ansible.builtin.file:
    path: "/etc/prometheus/rules/{{ item }}"
    state: absent
  with_items: "{{ alertrule_files.files | map(attribute='path') | map('basename') | list }}"
  when: item not in prometheus_alert_rules_files
  notify: reload prometheus
  become: true
  tags:
  - prometheus
  - prometheus_alertrules

- name: copy alert rules files
  ansible.builtin.copy:
    src: "prometheus/rules/{{ item }}"
    dest: "/etc/prometheus/rules/{{ item }}"
    mode: 0644
    owner: prometheus
    group: prometheus
    validate: "/usr/local/bin/promtool check rules %s"
  with_items: "{{ prometheus_alert_rules_files }}"
  notify: reload prometheus
  become: true
  tags:
  - prometheus
  - prometheus_alertrules

- name: register static targets
  ansible.builtin.find:
    paths: /etc/prometheus/file_sd
    file_type: file
    recurse: false
  register: static_target_files
  become: true
  tags:
  - prometheus
  - prometheus_config
  - prometheus_file_sd

- name: remove unmanaged static targets
  ansible.builtin.file:
    path: "/etc/prometheus/file_sd/{{ item }}"
    state: absent
  with_items: "{{ static_target_files.files | map(attribute='path') | map('basename') | list }}"
  when: item not in prometheus_static_targets_files
  notify: reload prometheus
  become: true
  tags:
  - prometheus
  - prometheus_config
  - prometheus_file_sd

- name: copy prometheus custom static targets
  ansible.builtin.copy:
    src: "prometheus/file_sd/{{ item }}"
    dest: "/etc/prometheus/file_sd/"
    force: true
    owner: prometheus
    group: prometheus
    mode: 0640
  notify: reload prometheus
  with_items: "{{ prometheus_static_targets_files }}"
  become: true
  tags:
  - prometheus
  - prometheus_config
  - prometheus_file_sd

- name: generate config file
  ansible.builtin.copy:
    content: "{{ prometheus_config | to_nice_yaml(indent=2, sort_keys=False) }}\n"
    dest: "/etc/prometheus/config.yml"
    owner: prometheus
    group: prometheus
    mode: 0644
    validate: "/usr/local/bin/promtool check config %s"
  notify: reload prometheus
  become: true
  tags:
  - prometheus
  - prometheus_config
  - prometheus_config_only

- name: generate webconfig file
  ansible.builtin.copy:
    content: "{{ prometheus_webconfig | to_nice_yaml(indent=2, sort_keys=False) }}\n"
    dest: "/etc/prometheus/web-config.yml"
    owner: "prometheus"
    group: "prometheus"
    mode: 0644
  notify: restart prometheus
  become: true
  when: prometheus_webconfig | length > 0
  tags:
  - prometheus
  - prometheus_config

- name: create systemd service unit
  ansible.builtin.template:
    src: prometheus.service.j2
    dest: /etc/systemd/system/prometheus.service
    owner: root
    group: root
    mode: 0644
  notify: restart prometheus
  become: true
  tags: prometheus

- name: ensure service is started and enabled
  ansible.builtin.systemd:
    daemon_reload: true
    name: prometheus
    enabled: true
    state: started
  become: true
  tags: prometheus
