---
argument_specs:
  main:
    short_description: Entry point for the alloy role.
    description:
    - Validate variables for the `alloy` role.
    options:
      alloy_service_enabled:
        description:
        - Controls `alloy_service_enabled` for the `alloy` role.
        required: false
        type: bool
      alloy_service_state:
        description:
        - Controls `alloy_service_state` for the `alloy` role.
        required: false
        type: str
      alloy_config_file:
        description:
        - Controls `alloy_config_file` for the `alloy` role.
        required: false
        type: str
      alloy_user:
        description:
        - Controls `alloy_user` for the `alloy` role.
        required: false
        type: str
      alloy_group:
        description:
        - Controls `alloy_group` for the `alloy` role.
        required: false
        type: str
      alloy_log_level:
        description:
        - Controls `alloy_log_level` for the `alloy` role.
        required: false
        type: str
      alloy_loki_endpoint:
        description:
        - Controls `alloy_loki_endpoint` for the `alloy` role.
        required: false
        type: str
      alloy_normal_logs_tenant:
        description:
        - Controls `alloy_normal_logs_tenant` for the `alloy` role.
        required: false
        type: str
      alloy_audit_logs_tenant:
        description:
        - Controls `alloy_audit_logs_tenant` for the `alloy` role.
        required: false
        type: str
      alloy_config:
        description:
        - Controls `alloy_config` for the `alloy` role.
        required: false
        type: dict
      alloy_firewall_enabled:
        description:
        - Controls `alloy_firewall_enabled` for the `alloy` role.
        required: false
        type: bool
      alloy_firewall_ports:
        description:
        - Controls `alloy_firewall_ports` for the `alloy` role.
        required: false
        type: list
      alloy_service_override:
        description:
        - Controls `alloy_service_override` for the `alloy` role.
        required: false
        type: dict
