---
argument_specs:
  main:
    short_description: Entry point for the blackbox_exporter role.
    description:
    - Validate variables for the `blackbox_exporter` role.
    options:
      proxy_env:
        description:
        - Controls `proxy_env` for the `blackbox_exporter` role.
        required: false
        type: dict
      blackbox_exporter_version:
        description:
        - Controls `blackbox_exporter_version` for the `blackbox_exporter` role.
        required: false
        type: str
      blackbox_exporter_log_level:
        description:
        - Controls `blackbox_exporter_log_level` for the `blackbox_exporter` role.
        required: false
        type: str
      blackbox_exporter_webconfig:
        description:
        - Controls `blackbox_exporter_webconfig` for the `blackbox_exporter` role.
        required: false
        type: dict
      blackbox_exporter_config_flags_extra:
        description:
        - Controls `blackbox_exporter_config_flags_extra` for the `blackbox_exporter` role.
        required: false
        type: dict
      blackbox_exporter_config:
        description:
        - Controls `blackbox_exporter_config` for the `blackbox_exporter` role.
        required: false
        type: str
      defaults_blackbox_exporter_config:
        description:
        - Controls `defaults_blackbox_exporter_config` for the `blackbox_exporter` role.
        required: false
        type: dict
      additional_blackbox_exporter_config:
        description:
        - Controls `additional_blackbox_exporter_config` for the `blackbox_exporter` role.
        required: false
        type: dict
