---
- name: restart unifi_poller
  ansible.builtin.systemd:
    daemon_reload: true
    name: "{{ unifi_poller_service_name }}"
    state: restarted
  become: true
  when: unifi_poller_manage_service
  tags: unifi_poller
